#!/bin/sh

APPDIR=$(dirname "$0")
java  -Djava.library.path="$APPDIR" -cp "$APPDIR/lib/NESMovieConverterFinal3.jar:$APPDIR/lib/core.jar:$APPDIR/lib/gifAnimation.jar:$APPDIR/lib/controlP5.jar" NESMovieConverterFinal3
